### ISSUE TITLE
Error in FilePathCache when a slash is added at the end of an asset url

### ISSUE THREAD

**Issue by e-belair** [jield-webdev/laminas-assetmanager#13]
When a slash is added at the end of an asset like `/js/scroll-to-top.js/`, it should return a 404 error. But there is an error in FilePathCache because the file is accepted by the manager:
```
Uncaught ErrorException: rename(public/assets/demo/js/AssetManagerFilePathCache_scroll-to-top.js,public/assets/demo/js/scroll-to-top.js/): Not a directory in /var/www/html/vendor/jield-webdev/laminas-assetmanager/src/Cache/FilePathCache.php:112
```
As you can see in the capture below, $filename doesn't have the trailing slash because pathinfo seems to remove it. But the cachedFile() return the filename as it has been detected in URL. So the rename() can't work.
![image](https://github.com/jield-webdev/laminas-assetmanager/assets/596562/bf0bf19f-fba8-4a77-ba41-69f02880e6a8)

The solutions could be to remove the trailing slash in return of cachedFile() method, or raise a 404 error on this URL.

I think the first solution would be better.

**Comment by japaveh** [comment]
This has been fixed in version 4
