### ISSUE TITLE
Make use of Laminas CLI

### ISSUE THREAD

**Issue by japaveh** [jield-webdev/laminas-assetmanager#6]
Currently this module relies on Laminas-console which was abandoned, so the CLI interface should be ported to laminas-cli

**Comment by ToshY** [comment]
Hey @japaveh 👋 

First off, thanks for making the library PHP 8.2 compatible. Do you have an estimation on when this will be implemented?

**Comment by japaveh** [comment]
@ToshY Support for cache warmup and purging is now available using Laminas CLI (in the development branch) let me know if it works for you

**Comment by ToshY** [comment]
Hey @japaveh 👋 

Sorry for the delayed response. I've just had time to test it, and the command itself seem to work fine 👍 Purging also works although I probably need to reconsider my own configuration as it also purged my entire directory 😅 [^1].

Could you tag a new release when you have the time? Thanks in advance!

[^1]: I specified in the config `'dir' => 'root'`, so it also purged things like `root/index.php` etc. I'm not sure how this worked before (never used purging), but just purging the directories that were created would seems more reasonable. Maybe an enhancement for another time.

**Comment by japaveh** [comment]
@ToshY Code has been merged, I also added a filter to only purge .css and .js files. Let me know if this helps for you
