### ISSUE TITLE
Incompatible with PHP 8.2

### ISSUE THREAD

**Issue by FWest98** [jield-webdev/laminas-assetmanager#8]
It seems like currently this library is incompatible with PHP 8.2. This is because the library creates dynamic properties on various `Asset` instances, which is deprecated from PHP 8.2 onwards. An example of where this occurs: https://github.com/jield-webdev/laminas-assetmanager/blob/master/src/Resolver/PathStackResolver.php#L187, but there are probably other occurrences as well.

**Comment by japaveh** [comment]
HI @FWest98 , I release v3.0 a few moments ago which is PHP8.2 compatible. I tested the resources I use but if you find any issues with other assets or resolvers where the dynamic properties are a problem, please let me know
